name: Deploy

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t bmap-ai:${{ github.sha }} .
    
    - name: Push to registry
      run: |
        echo "Pushing to registry..."
        # docker push logic here
    
    - name: Deploy to production
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Deploying version ${GITHUB_REF#refs/tags/}"